# Generated by Django 4.0 on 2022-01-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, null=True)),
                ('reciever', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date_tran', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='curr_balance',
            field=models.IntegerField(default=0),
        ),
    ]
