# Generated by Django 4.0 on 2022-01-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transfer_alter_customerdetail_curr_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='reciever',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='sender',
            new_name='sender_name',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='date_tran',
            new_name='trans_date',
        ),
    ]
